Correct compiler error, missing 'value' initializer
struct ibpi2value is a structure which contains 2 unsigned integers.  In
a number of cases the code was not initializing a value for the last value
in the pair in struct ibpi2value ibpi_to_attention.  This was raised when
using clang compiler.

vmdssd.c:49:27: error: missing field 'value' initializer
[-Werror,-Wmissing-field-initializers]
        {LED_IBPI_PATTERN_UNKNOWN}

dellssd.c:74:27: error: missing field 'value' initializer
[-Werror,-Wmissing-field-initializers]
        {LED_IBPI_PATTERN_UNKNOWN}

amd_ipmi.c:57:27: error: missing field 'value'
initializer [-Werror,-Wmissing-field-initializers]
        {LED_IBPI_PATTERN_UNKNOWN}

npem.c:76:27: error: missing field 'value'
initializer [-Werror,-Wmissing-field-initializers]
        {LED_IBPI_PATTERN_UNKNOWN}

Signed-off-by: Tony Asleson <tasleson@redhat.com>