configure.ac: Force error on compiler CFLAG check
The local function AX_AM_CFLAGS_ADD did not pass -Werror in the 4th
argument to the function AX_CHECK_COMPILE_FLAG, thus when a compiler
flag check produced a warning it would pass the configure but would
fail the compile as we treat warnings as error during compile.

Force an error so that the option is not included for compilers that
don't support a compiler flags.  Clag appears to not support the
following:

error: unknown warning option '-Wformat-overflow=2'; did you mean
	'-Wshift-overflow'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wwrapv'
	[-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wformat-truncation=1'
	[-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wformat-signedness'
	[-Werror,-Wunknown-warning-option]

Signed-off-by: Tony Asleson <tasleson@redhat.com>