ledctl: replace on_exit() by atexit()
Replace on_exit() by atexit() to avoid the following musl build failure
raised since bcb9042 ("ledctl: Remove enum ledctl_status_code_t")
which partially reverted f08dd2c ("Fix build with Musl libc (#139)")

/home/buildroot/autobuild/instance-3/output-1/host/lib/gcc/arm-buildroot-linux-musleabi/12.3.0/../../../../arm-buildroot-linux-musleabi/bin/ld: ledctl-ledctl.o: in function `main':
ledctl.c:(.text.startup+0x140): undefined reference to `on_exit'

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>